language: node_js
node_js: 
  - "stable"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=majo1569-github -Dsonar.projectKey=calculator -Dsonar.sources='./app' -X
jobs:
  include:
    - stage: unit tests
      script: npm test
    - stage: deploy
      script: npm run start
      deploy: 
        provider: heroku
        api_key: b5658fe9-7fa1-431f-bd0f-8a699b2d9e2d
        strategy: git 
        app: apjs-ci
        on:
            repo: majo1569/appjs-ci
notifications:
  slack: naksinc:3gS2KmrT2PJDARWHqAmdK3IC            