language: node_js
node_js: 
  - "stable"
jobs:
  include:
    - stage: unit tests
      script: npm test
    -stage: deploy
      deploy: 
        provider: heroku
        api_key: b5658fe9-7fa1-431f-bd0f-8a699b2d9e2d
        app: apjs-ci
        on:
            repo: majo1569/appjs-ci
            